### ISSUE TITLE
bimp compile lots of warning

### ISSUE THREAD

**Issue by region51** [alessandrofrancesconi/gimp-plugin-bimp#103]
```
warning: 'gdk_pixbuf_from_pixdata' is deprecated [-Wdeprecated-declarations]
warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
warning: implicit declaration of function 'abs' [-Wimplicit-function-declaration]
warning: ignoring return value of 'readlink', declared with attribute warn_unused_result [-Wunused-result]
warning: "INPUT_W" redefined
```

and more 
http://koji.russianfedora.pro/kojifiles/packages/gimp-bimp-plugin/1.16/1.fc23.R/data/logs/x86_64/build.log

this is not good

**Comment by region51** [comment]
ping???

**Comment by alessandrofrancesconi** [comment]
Most of the warnings that GCC produces can be safely ignored since they don't represent a real code issue.
Regarding the usage of deprecated functions, this is due to the fact that we need retro compatibility with GTK+ 2.16 since BIMP for Win32 depends on it.

________________________________
Da: Maxim Orlov<mailto:notifications@github.com>
Inviato: ‎22/‎01/‎2016 14:28
A: alessandrofrancesconi/gimp-plugin-bimp<mailto:gimp-plugin-bimp@noreply.github.com>
Oggetto: Re: [gimp-plugin-bimp] bimp compile lots of warning (#103)

ping???

---
