### ISSUE TITLE
User error?

### ISSUE THREAD

**Issue by Mahi-Mai** [alessandrofrancesconi/gimp-plugin-bimp#105]
I'm trying to use BIMP to slice up a batch of images using the guillotine function.  I put in the steps for creating horizontal and vertical guides (5 guides total), then finish with the guillotine function.  However, when I run the set it only returns a copy of the original image to the destination folder.  Are these features not functional yet, or am I using them incorrectly?

Thanks!

**Comment by alessandrofrancesconi** [comment]
I can reproduce the problem. The cause is the plugin-in-guillotine manipulation itself, that has a non-compatible behavior under BIMP. The supported plugins on BIMP must take a single image and return only **one ** other copy of such file, modified.
The guillotine, instead, is meant to split the image in various parts so BIMP doesn't know which one of the images has to been saved.

I know I should remove plugin-in-guillotine from the list, as well as all other plugins that create multiple output images, but right now I cannot find an easy way to check this property at runtime.

**Comment by Mahi-Mai** [comment]
Ach!  What a bummer...  Okay.  Thanks for getting back to me!

**Comment by Brianckeith** [comment]
A solution might be to use Guillotine-into-Layers (http://registry.gimp.org/node/19886), which outputs the split-up graphics into a single file as layers instead of multiple files.

**Comment by alessandrofrancesconi** [comment]
Interesting! 👍
