### ISSUE TITLE
Plug-in istall fail - makewin.bat fail either

### ISSUE THREAD

**Issue by yvesbe** [alessandrofrancesconi/gimp-plugin-bimp#122]
Hi there, 

tryed to install the plug-in on windows. the plug-in tells me that gimp isn't installed. But it is :)

- Gimp 2.8
- Windows 8.1 FRENCH (dunno if it's important)

path for gimp : 
C:\Program Files\GIMP 2\              ( not C:\Program Files (x86)\GIMP 2\ )

batch makewin doesn't work on my computer: (file not found)

**Comment by alessandrofrancesconi** [comment]
BIMP installer looks for the GIMP installation folder by reading the following Windows registry key: 
`Software\Microsoft\Windows\CurrentVersion\Uninstall\GIMP-2_is1`

Ensure it is present using the Regedit tool. Since this key is created by the official GIMP installer, I'm wondering if you used another method to install GIMP... (is it the portable version, maybe?)
You can try to reinstall GIMP using the installer [here](https://download.gimp.org/mirror/pub/gimp/v2.8/windows/gimp-2.8.16-setup-6.exe)

**Comment by yvesbe** [comment]
What could i say ? 
1 - you repaired my gimp that was still working but not that correctly (and i didn't knew it)
2 - your plug-in istalled itself properly 
3 - i gave it a try and the result was exactly what i expected. 

hi five for you, thanks a lot.

**Comment by alessandrofrancesconi** [comment]
:+1:
