### ISSUE TITLE
fails on ubuntu 18.10

### ISSUE THREAD

**Issue by xaver13** [alessandrofrancesconi/gimp-plugin-bimp#178]
src/manipulation-gui/gui-resize.c: In function ‘bimp_resize_save’:
src/manipulation-gui/gui-resize.c:283:40: error: ‘GIMP_INTERPOLATION_LANCZOS’ undeclared (first use in this function); did you mean ‘GIMP_INTERPOLATION_LOHALO’?
         orig_settings->interpolation = GIMP_INTERPOLATION_LANCZOS;
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                        GIMP_INTERPOLATION_LOHALO

**Comment by alessandrofrancesconi** [comment]
Latest version [v2.0](https://github.com/alessandrofrancesconi/gimp-plugin-bimp/releases/tag/v2.0) should fix this issue. Please give it a try!

**Comment by alessandrofrancesconi** [comment]
It's because you are compiling using GIMP 2.8 or older.
New BIMP 2.0 code can be compiled starting from GIMP 2.10 (that's why yours does not recognize for example GIMP_INTERPOLATION_LOHALO).


---- mconsidine ha scritto ----


Actually, I'm getting this sort of error as well after issuing "make"

which gimptool-2.0 && which pcre-config &&
gcc -o ./bin/bimp -Wall -O2 -Wno-unused-variable -Wno-pointer-sign src/.c src/manipulation-gui/.c src/images/*.c -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/gimp-2.0 -lgimpui-2.0 -lgimpwidgets-2.0 -lgimpmodule-2.0 -lgimp-2.0 -lgimpmath-2.0 -lgimpconfig-2.0 -lgimpcolor-2.0 -lgimpbase-2.0 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lpcre -lm -DGIMP_DISABLE_DEPRECATED
/usr/bin/gimptool-2.0
/usr/bin/pcre-config
src/bimp-gui.c: In function ‘bimp_show_error_dialog’:
src/bimp-gui.c:1086:5: warning: format not a string literal and no format arguments [-Wformat-security]
);
^
In file included from src/bimp-manipulations-gui.c:18:0:
src/manipulation-gui/gui-watermark.h:7:0: warning: "INPUT_W" redefined
#define INPUT_W 160
^
In file included from src/bimp-manipulations-gui.c:15:0:
src/manipulation-gui/gui-color.h:15:0: note: this is the location of the previous definition
#define INPUT_W 200
^
src/bimp-manipulations-gui.c: In function ‘bimp_open_editwindow’:
src/bimp-manipulations-gui.c:49:14: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
save = &bimp_resize_save;
^
src/bimp-manipulations-gui.c:53:14: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
save = &bimp_crop_save;
^
src/bimp-manipulations-gui.c:57:14: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
save = &bimp_fliprotate_save;
^
src/bimp-manipulations-gui.c:61:14: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
save = &bimp_color_save;
^
src/bimp-manipulations-gui.c:65:14: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
save = &bimp_sharpblur_save;
^
src/bimp-manipulations-gui.c:69:14: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
save = &bimp_changeformat_save;
^
src/bimp-manipulations-gui.c:73:14: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
save = &bimp_watermark_save;
^
src/bimp-manipulations-gui.c:77:14: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
save = &bimp_rename_save;
^
src/bimp-manipulations-gui.c:81:14: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
save = &bimp_userdef_save;
^
src/bimp-operate.c: In function ‘apply_resize’:
src/bimp-operate.c:547:13: error: ‘GIMP_LAYER_MODE_NORMAL_LEGACY’ undeclared (first use in this function)
GIMP_LAYER_MODE_NORMAL_LEGACY
^
src/bimp-operate.c:547:13: note: each undeclared identifier is reported only once for each function it appears in
src/bimp-operate.c:565:37: error: ‘GIMP_FILL_BACKGROUND’ undeclared (first use in this function)
gimp_drawable_fill(layerId, GIMP_FILL_BACKGROUND);
^
src/bimp-operate.c:569:9: warning: implicit declaration of function ‘gimp_item_transform_translate’ [-Wimplicit-function-declaration]
gimp_item_transform_translate(layerId, -abs(view_w - final_w) / 2, -abs
^
src/bimp-operate.c:569:49: warning: implicit declaration of function ‘abs’ [-Wimplicit-function-declaration]
gimp_item_transform_translate(layerId, -abs(view_w - final_w) / 2, -abs
^
src/bimp-operate.c: In function ‘apply_color’:
src/bimp-operate.c:698:23: warning: implicit declaration of function ‘gimp_drawable_brightness_contrast’ [-Wimplicit-function-declaration]
success = gimp_drawable_brightness_contrast(
^
src/bimp-operate.c:715:23: warning: implicit declaration of function ‘gimp_drawable_levels_stretch’ [-Wimplicit-function-declaration]
success = gimp_drawable_levels_stretch(out->drawable_ids[i]);
^
src/bimp-operate.c:741:31: warning: implicit declaration of function ‘gimp_drawable_curves_spline’ [-Wimplicit-function-declaration]
success = gimp_drawable_curves_spline(out->drawable_ids[i],
^
src/bimp-operate.c: In function ‘image_save’:
src/bimp-operate.c:1117:17: error: ‘GIMP_CONVERT_DITHER_FS’ undeclared (first use in this function)
GIMP_CONVERT_DITHER_FS,
^
src/bimp-operate.c:1118:17: error: ‘GIMP_CONVERT_PALETTE_GENERATE’ undeclared (first use in this function)
GIMP_CONVERT_PALETTE_GENERATE,
^
src/bimp-operate.c: In function ‘image_save_gif’:
src/bimp-operate.c:1164:9: error: ‘GIMP_CONVERT_DITHER_FS’ undeclared (first use in this function)
GIMP_CONVERT_DITHER_FS,
^
src/bimp-operate.c:1165:9: error: ‘GIMP_CONVERT_PALETTE_GENERATE’ undeclared (first use in this function)
GIMP_CONVERT_PALETTE_GENERATE,
^
src/bimp-operate.c: At top level:
src/bimp-operate.c:1242:17: warning: ‘image_save_heif’ defined but not used [-Wunused-function]
static gboolean image_save_heif(image_output out, int quality, gboolean lossles
^
src/bimp-utils.c: In function ‘get_bimp_localedir’:
src/bimp-utils.c:172:5: warning: ignoring return value of ‘readlink’, declared with attribute warn_unused_result [-Wunused-result]
readlink("/proc/self/exe", path, bufsize);
^
src/manipulation-gui/gui-resize.c: In function ‘bimp_resize_save’:
src/manipulation-gui/gui-resize.c:283:40: error: ‘GIMP_INTERPOLATION_NOHALO’ undeclared (first use in this function)
orig_settings->interpolation = GIMP_INTERPOLATION_NOHALO; // replaces L
^
src/manipulation-gui/gui-resize.c:283:40: note: each undeclared identifier is reported only once for each function it appears in
src/manipulation-gui/gui-resize.c:286:40: error: ‘GIMP_INTERPOLATION_LOHALO’ undeclared (first use in this function)
orig_settings->interpolation = GIMP_INTERPOLATION_LOHALO;
^
Makefile:7: recipe for target 'make' failed
make: *** [make] Error 1

This is on Linux Mint 18.3 "Sylvia" (16.04/xenial; kernel 4.15.0-38-generic; Cinnamon 3.6.7).
Thoughts?

**Comment by alessandrofrancesconi** [comment]
The way is to install the "development package" of GIMP >=2.10, not really the "sources". In Linux distros it's usually named "gimp-dev", or sort of.


---- mconsidine ha scritto ----


Hi,
Thanks for the reply. So I had uninstalled GIMP and installed GIMP 2.10.8 via flatpak, as that was the only way short of compiling from source to get it installed (no binary available for 16.04). So it looks like compiling BIMP from source assumes that GIMP source is available or was used to install GIMP? Or do I misunderstand? Can you suggest how I can point the BIMP "make" "process" to 2.10.x source?
Thanks!
