### ISSUE TITLE
Resize proportionally

### ISSUE THREAD

**Issue by edikaufmann** [alessandrofrancesconi/gimp-plugin-bimp#226]
… I must miss something

In GIMP: Image -->resize; I have the option of proportionally resize (%, px)
In BIMP:
Resize does NOT have that option; i.e. to resize proportionally I have to set the e.g. both % (width and height).
Same for PX: I'd like e.g. to set a certain width and have BIMP to calculate the height proportionally.

as said; I might miss the obvious …
thanks for your time and help
ed k

**Comment by scribblemaniac** [comment]
By what proportions? You could want to scale your image to an number of proportions which is why you usually have to specify the width and height. I'm assuming what you mean to say is that you want to scaled your image while preserving the proportions of the input image. In that case you can set Aspect Ratio to Preserve and disable the dimension you do not want to specify.

**Comment by edikaufmann** [comment]
oops, (I knew) I missed the obvious .. your answer cleared it immediately ..thanks
definitely time for a donation!, ed
