### ISSUE TITLE
MacOS installer says it cannot find plugin folder

### ISSUE THREAD

**Issue by Bazzer485** [alessandrofrancesconi/gimp-plugin-bimp#263]

**Comment by alessandrofrancesconi** [comment]
Is it MacOS? Which version (Catalina, Big Sur)?
Did you install GIMP from official distribution? https://www.gimp.org/downloads/

Please open GIMP and tell me what settings are stored in Preferences -> Folders (click +) -> Plug-Ins

![image](https://user-images.githubusercontent.com/1595223/105315206-4639b400-5bbf-11eb-8ff6-a5bff26c7852.png)
![image](https://user-images.githubusercontent.com/1595223/105315217-49cd3b00-5bbf-11eb-9ba0-f5ffa8a4202a.png)

**Comment by Bazzer485** [comment]
My Macbook pro is a 2012 running Catalina  I downloaded Gimp from Gimp.org  The plug-on folder contents are as shown above.  I ran the Bimp install program as instructed 
Barry

**Comment by alessandrofrancesconi** [comment]
Meanwhile, you can install it manually: just copy the file "bimp" to one of the paths listed in your GIMP settings (see my screenshot). Let me know if this works.

**Comment by alessandrofrancesconi** [comment]
Also check if these paths actually exists in your system!

**Comment by 73941** [comment]
macOS Mojave Version 10.14.6

I have only been able to make it work using MacPorts GIMP and the Linux install method.

Tried moving the bimp folder to "Users/me/Documents/bimp_plugin/" and adding this as a plug-in path, but it still did not show up in the plug-in browser. 

Despite installing with the Linux method, the plug-in still would not work with the official MacOS release of GIMP 2.10.22
It would show up in the File menu of the MacOS release, but would return an error when trying to start it.

I have since tried reinstalling the MacOS release of BIMP, using the Unix executable. Since then, the plug-in has stopped showing up in both the plug-in browser, and the File menu of GIMP 2.10.22 for MacOS. 
Despite this change, the latest MacPorts version of GIMP still runs BIMP with no problems.

**Comment by chowardart** [comment]
OK, my issue... It would appear that the only plug-ins folder exists within the application only, as in Applications/GIMP2.10.app/Contents/Resources/lib/plugins...
I tried to move the BIMP plugin into there but I get an error message - send to Apple, etc.
This is on BigSur 11.2.1
I got the latest BIMB and GIMP, I tried installing using MacPorts; took awhile with GIMP install, but it's in, and still no plug-ins folder under Users/NAME/ApplicationSupport/GIMP/2.10
Can anyone cast a light on why mine's being so difficult?...

**Comment by scribblemaniac** [comment]
> I got the latest BIMB and GIMP, I tried installing using MacPorts; took awhile with GIMP install, but it's in, and still no plug-ins folder under Users/NAME/ApplicationSupport/GIMP/2.10
Can anyone cast a light on why mine's being so difficult?...

You can create a new folder if it does not exist.

**Comment by chowardart** [comment]
Hmm... It doesn’t matter if there are two plug-ins folders?
Also, to place BIMP into a newly created folder; should I place the entire BIMP folder into the plug-ins folder, or is just the executable enough?...

**Comment by alessandrofrancesconi** [comment]
> Hmm... It doesn’t matter if there are two plug-ins folders?

No, just ensure that folder is listed in GIMP -> Preferences -> Folders

> Also, to place BIMP into a newly created folder; should I place the entire BIMP folder into the plug-ins folder, or is just the executable enough?...

In the new folder, place "bimp" executable + "bimp-locale" folder if you need multilanguage

> EDIT: Now I get a "“bimp” cannot be opened because the developer cannot be verified." error, but I'm only offered to cancel or delete...

This is normal due to Apple Gatekeeper. When the message appear, close GIMP, open System Preferences -> Security & Privacy -> General tab. Click "Allow Anyway" to unlock the BIMP executable. Open GIMP again, this time the Warning message lets you click the "Open" button and continue.

> EDIT 2: I tried to use Terminal to open BIMP directly, and this was part of the error code:
> Dyld Error Message:
> Library not loaded: @rpath/libatk-1.0.0.dylib
> Referenced from: /Users/USER/Library/Application Support/GIMP/*/bimp
> Reason: Incompatible library version: bimp requires version 23610.0.0 or later, but libatk-1.0.0.dylib provides version 23210.0.0

Are you sure you are using **GIMP 2.10.22 downloaded from [official website](https://www.gimp.org/downloads/)**? It is the only version that should work with my "BIMP for MacOS" package. Double check that please.

**Comment by chowardart** [comment]
Ah! I have version 2.10.14! Fixing now, will try all this - thanks!...

**Comment by chowardart** [comment]
Yes sir! Working, tested, and working!
I'd be glad to share my experience with this! I know at least one forum where I can help somebody...
Again, thank you! This was one feature of Photoshop that it did not have when I first began using GIMP, and now, this is a BIG improvement!
