### ISSUE TITLE
Remembering the bimp set up

### ISSUE THREAD

**Issue by orish1** [alessandrofrancesconi/gimp-plugin-bimp#277]
Hi, I found that every time I wanted to run a batch job, I had to start again from scratch: adding the files and adding  the batch process chain and configuring them.

REQUEST

Please could you 

1) Remember the same configuration of bimp when closing the dialog box and reopening it later. All the added files, the process chain, with the individual configurations for each of the edits.

2) Provide a mechanism to save a batch job (as a template or something) so that it can be loaded up and applied again in the future, for a different set of files, say.

Thanks :)

**Comment by alessandrofrancesconi** [comment]
"Add -> Save/Load set" lets you restore your batch sequence from a backup file!

Alessandro

________________________________
From: orish1 ***@***.***>
Sent: Sunday, June 6, 2021 5:47:48 AM
To: alessandrofrancesconi/gimp-plugin-bimp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [alessandrofrancesconi/gimp-plugin-bimp] Remembering the bimp set up (#277)


Hi, I found that every time I wanted to run a batch job, I had to start again from scratch: adding the files and adding the batch process chain and configuring them.

REQUEST

Please could you

  1.  Remember the same configuration of bimp when closing the dialog box and reopening it later. All the added files, the process chain, with the individual configurations for each of the edits.

  2.  Provide a mechanism to save a batch job (as a template or something) so that it can be loaded up and applied again in the future, for a different set of files, say.

Thanks :)
