### ISSUE TITLE
Windows defender flagging virus

### ISSUE THREAD

**Issue by dssilver** [alessandrofrancesconi/gimp-plugin-bimp#278]
I'm downloading for the first time on Windows and Defender is popping up and saying virus detected.  I see there was a similar issue in the past which was closed.  Any comment on this currently?  Should I just ignore it?

**Comment by dssilver** [comment]
I've tried downloading the windows installer version 2.5 and 2.4 and each time Windows says severe threat detected, trojan.

**Comment by msantiago4** [comment]
Before downloading ../v2.5/gimp-plugin-bimp_win32.exe into my system today, I submitted the file to VirusTotal for virus scanning before using it myself. Well, VirusTotal has reported viruses.
Is this a real problem? In light of dssilver's report I am very concerned. Please advise!

**Comment by scribblemaniac** [comment]
Currently, 4/88 scanners reported an issue with the latest exe. Given that it is an NSIS installer, a few false positives with less reputable security vendors is not that unusual. As an open source program, you are free to look through the source code yourself and build it from the source rather than using the installer. All programs you install or use could potentially be malicious (or exploited maliciously by others), so at the end of the day you are the one that has to decide what is an acceptable risk for your own computer.
