### ISSUE TITLE
Image Compression does nothing?

### ISSUE THREAD

**Issue by Baptor1337** [alessandrofrancesconi/gimp-plugin-bimp#327]
I've tried both the new and older versions. I have GIMP 2.10 and Windows 10. Plugin installed just fine. Opened up a BMP and asked it to convert it to a JPG. After selecting quality level it ran a progress bar and said it was converted successfully. However the image is still a BMP and no JPG was created either. I've tried it multiple times with different images and it never actually does anything.

**Comment by alessandrofrancesconi** [comment]
Are you sure you are looking into the right output directory? Check the directory selector to the right of the input files list.

**Comment by Baptor1337** [comment]
Yes, I checked the output directory and even searched my entire hard drive for the name of the file to make sure it was not being stashed somewhere else. Also, I tried sending it to the Desktop and it did not work. As far as permissions, my account is the Administrator and other programs have no issues writing or changing things. I can even edit individual files in GIMP and it will work but if I use BIMP it does not.

**Comment by alessandrofrancesconi** [comment]
Is "Change Format and Compression" the only step you are using?

Also, can you try both these tests:
 - Use a different manipulation step instead of Change Format, example Crop
 - Use Change Format but with another file type, example PNG

This is to isolate the issue. In both cases, save to a different folder so input files don't get overwritten. This is to ensure that the issue is
